"""Art. 50 transparency disclosure helper.

Prepends a human-readable AI-generated disclosure to model output so that the
proxy can satisfy the EU AI Act transparency obligation. Alongside the human
sentence it embeds a machine-readable marker in the body and the HTTP layer sets
the `X-AI-Generated` header.

Note on scope: the in-body marker is a pragmatic, copy/paste-durable signal, not
a cryptographic provenance standard. Robust, interoperable marking of synthetic
content (e.g. C2PA / Content Credentials) is out of scope for a text proxy, so
Art. 50(2) coverage is partial by design.
"""

from . import config  # noqa: F401  (kept for package-consistent imports)

HEADER = "X-AI-Generated"
# Human-readable disclosures by language. English is the canonical fallback for
# any unsupported code; Art. 50 requires a clear notice in an understandable
# language, so the proxy serves the caller's preferred one when it can.
DISCLOSURES = {
    "en": "⚠️ This content was generated by AI.",
    "it": "⚠️ Questo contenuto è stato generato dall'IA.",
    "de": "⚠️ Dieser Inhalt wurde von KI generiert.",
    "fr": "⚠️ Ce contenu a été généré par une IA.",
    "es": "⚠️ Este contenido ha sido generado por IA.",
}
DISCLOSURE = DISCLOSURES["en"]  # backwards-compatible default
# Machine-readable counterpart to the human disclosure. Unlike the HTTP header it
# travels with the body through copy/paste and storage, giving downstream tooling
# a stable token to detect AI-generated content (EU AI Act Art. 50(2)).
MARKER = "<!-- ai-generated: true; generator: AEGIS -->"


def resolve_lang(accept_language: str = None) -> str:
    """Pick a supported disclosure language.

    Prefers the first supported tag in an Accept-Language header, then the
    configured default (AEGIS_DISCLOSURE_LANG), then English.
    """
    if accept_language:
        for part in accept_language.split(","):
            code = part.split(";")[0].strip().lower()[:2]
            if code in DISCLOSURES:
                return code
    default = (config.DISCLOSURE_LANG or "en")
    return default if default in DISCLOSURES else "en"


def inject(text: str, lang: str = None) -> str:
    """Prepend the human disclosure and the machine-readable marker, once.

    `lang` selects the disclosure language (defaults to the configured one).
    Idempotency keys on the marker, so re-injecting already-disclosed text in
    any language is a no-op.
    """
    text = text or ""
    if MARKER in text:
        return text
    code = (lang or config.DISCLOSURE_LANG or "en").lower()
    disclosure = DISCLOSURES.get(code, DISCLOSURES["en"])
    return f"{disclosure}\n{MARKER}\n\n{text}"
