"""Art. 50 transparency disclosure helper.

Prepends a human-readable AI-generated disclosure to model output so that the
proxy can satisfy the EU AI Act transparency obligation. The HTTP layer also
sets the `X-AI-Generated` header alongside this in-body disclosure.
"""

from . import config  # noqa: F401  (kept for package-consistent imports)

HEADER = "X-AI-Generated"
DISCLOSURE = "⚠️ This content was generated by AI."


def inject(text: str) -> str:
    """Prepend the disclosure exactly once (idempotent)."""
    text = text or ""
    if text.startswith(DISCLOSURE):
        return text
    return f"{DISCLOSURE}\n\n{text}"
