// LiveFire — the cinematic cascade. One attack, driven entirely by the real
// /api/chat trace, animated down a vertical AEGIS pipeline with a GSAP timeline.
// Four honest outcomes: blocked-at-input, sanitized-at-output, allowed-clean,
// and (guard off) the unprotected leak.
//
// The resting DOM is the FINISHED state: the GSAP timeline only enhances it.
// When motion is reduced or the tab is hidden (requestAnimationFrame is paused
// there, so a timeline would never advance) we snap straight to that final
// state — the cascade never ships blank.

import { useLayoutEffect, useRef } from 'react'
import type { ReactNode } from 'react'
import gsap from 'gsap'
import { ArtChip, Sev, VerdictBadge } from './primitives'
import type { AuditEvent, ChatResponse, ChatTrace, DetectionResult } from '../types'

type StageKey = 'ingest' | 'input' | 'llm' | 'output' | 'disclosure' | 'audit'
type LiveFireKind = 'blocked' | 'sanitized' | 'allowed' | 'unprotected'

interface LfStage {
  key: StageKey
  title: string
  sub: string
  art?: string
  icon: ReactNode
}

interface LiveFireModel {
  kind: LiveFireKind
  stop: StageKey
  bypassed: StageKey[]
  banner: { tag: string; text: string }
  reads: Record<string, string>
  detection?: DetectionResult
  sealed: AuditEvent | null
}

const DISCLOSURE = '⚠️ This content was generated by AI.'

const ICON: Record<string, ReactNode> = {
  prompt: <path d="M5 6l4 4-4 4M11 15h5" />,
  shield: <path d="M10 3l6 2.5V10c0 4.2-6 7-6 7s-6-2.8-6-7V5.5L10 3z" />,
  chip: <path d="M6.5 6.5h7v7h-7zM10 3v3.5M10 13.5V17M3 10h3.5M13.5 10H17" />,
  scan: (
    <>
      <circle cx="9" cy="9" r="4.4" />
      <path d="M12.4 12.4L17 17" />
    </>
  ),
  info: <path d="M10 17a7 7 0 100-14 7 7 0 000 14zM10 9.2v4M10 6.6v.2" />,
  lock: <path d="M5 9.5h10v7H5zM7 9.5V7a3 3 0 016 0v2.5" />,
}

const STAGES: LfStage[] = [
  { key: 'ingest', title: 'Ingest', sub: 'user prompt', icon: ICON.prompt },
  { key: 'input', title: 'Input Detection', sub: 'rules + judge', art: 'Art.15(5)', icon: ICON.shield },
  { key: 'llm', title: 'LLM', sub: 'Regolo', icon: ICON.chip },
  { key: 'output', title: 'Output Scan', sub: 'PII / secret', art: 'Art.15(5)', icon: ICON.scan },
  { key: 'disclosure', title: 'Disclosure', sub: 'AI label', art: 'Art.50', icon: ICON.info },
  { key: 'audit', title: 'Audit · Seal', sub: 'hash chain', art: 'Art.12', icon: ICON.lock },
]
const IDX = Object.fromEntries(STAGES.map((s, i) => [s.key, i])) as Record<StageKey, number>

// leak signatures, only used to highlight what genuinely surfaced in a reply.
// the dash class covers the unicode hyphens (‑ – —) models often emit.
const LEAK_RE =
  /(AEGIS[-‐-―]FLAG[-‐-―][A-Z0-9]{3,6}[-‐-―][A-Z0-9]{3,6}|[\w.+-]+@[\w-]+\.[\w.-]+|\b(?:\d[ -]?){13,19}\b|\b\d{3}-\d{2}-\d{4}\b|\b(?:demo-api|sk)-[\w-]{5,}\b)/g

function splitLeaks(text: string) {
  const out: Array<{ t: string; leak?: boolean }> = []
  let last = 0
  let m: RegExpExecArray | null
  LEAK_RE.lastIndex = 0
  while ((m = LEAK_RE.exec(text))) {
    if (m.index > last) out.push({ t: text.slice(last, m.index) })
    out.push({ t: m[0], leak: true })
    last = m.index + m[0].length
  }
  if (last < text.length) out.push({ t: text.slice(last) })
  return out
}

function splitRedactions(text: string) {
  return text.split(/(\[REDACTED\])/g).map((t) => ({ t, redacted: t === '[REDACTED]' }))
}

function shortHash(h?: string) {
  return h ? h.slice(0, 16) : '—'
}

// derive the human verdict + the per-stage readout lines from the raw trace
function read(res: ChatTrace, guard: boolean): LiveFireModel {
  const di = (res.input_detection || {}) as DetectionResult
  const od = (res.output_detection || {}) as DetectionResult
  const ev = (res.events || []).filter((e) => e.hash)
  const sealed = ev[ev.length - 1] || null
  const caughtBy = di.judge_used ? 'LLM judge' : (di.matched && di.matched[0]) || di.rule_id

  if (!guard) {
    return {
      kind: 'unprotected',
      stop: 'output',
      bypassed: ['input', 'output', 'disclosure', 'audit'],
      banner: { tag: 'UNPROTECTED', text: 'no guardrail — the model answered directly' },
      reads: { input: 'bypassed', llm: 'responded', output: 'bypassed', disclosure: 'none', audit: 'no record' },
      sealed: null,
    }
  }
  if (res.blocked) {
    return {
      kind: 'blocked',
      stop: 'input',
      bypassed: [],
      banner: { tag: 'BLOCKED', text: 'caught before the model — sealed as evidence' },
      reads: {
        input: `${(di.verdict || '').replace(/_/g, ' ')} · sev ${di.severity} · ${caughtBy}`,
        llm: 'never reached',
        output: 'never reached',
        disclosure: '—',
        audit: sealed ? `#${sealed.id} · sealed` : 'sealed',
      },
      detection: di,
      sealed,
    }
  }
  if (res.sanitized) {
    return {
      kind: 'sanitized',
      stop: 'audit',
      bypassed: [],
      banner: { tag: 'SANITIZED', text: 'model leaked — AEGIS redacted it at the output' },
      reads: {
        input: 'clean',
        llm: 'responded',
        output: `${(od.verdict || 'leak').replace(/_/g, ' ')} · redacted`,
        disclosure: res.transparency ? 'Art.50 label injected' : 'labelled',
        audit: sealed ? `#${sealed.id} · sealed` : 'sealed',
      },
      detection: od,
      sealed,
    }
  }
  return {
    kind: 'allowed',
    stop: 'audit',
    bypassed: [],
    banner: { tag: 'ALLOWED', text: 'clean — disclosed and logged' },
    reads: {
      input: 'clean',
      llm: 'responded',
      output: 'clean',
      disclosure: res.transparency ? 'Art.50 label injected' : 'labelled',
      audit: sealed ? `#${sealed.id} · logged` : 'logged',
    },
    detection: di,
    sealed,
  }
}

// the finished state for every kind — stage classes + pipe-segment classes
const FINAL: Record<LiveFireKind, { s: Record<string, string>; l: Record<string, string> }> = {
  blocked: {
    s: { ingest: 'is-pass', input: 'is-block', llm: 'is-skip', output: 'is-skip', disclosure: 'is-skip', audit: 'is-seal' },
    l: { 0: 'is-pass', 1: 'is-severed', 2: 'is-severed', 3: 'is-severed', 4: 'is-severed' },
  },
  sanitized: {
    s: { ingest: 'is-pass', input: 'is-pass', llm: 'is-pass', output: 'is-warn', disclosure: 'is-pass', audit: 'is-seal' },
    l: { 0: 'is-pass', 1: 'is-pass', 2: 'is-pass', 3: 'is-pass', 4: 'is-pass' },
  },
  allowed: {
    s: { ingest: 'is-pass', input: 'is-pass', llm: 'is-pass', output: 'is-pass', disclosure: 'is-pass', audit: 'is-seal' },
    l: { 0: 'is-pass', 1: 'is-pass', 2: 'is-pass', 3: 'is-pass', 4: 'is-pass' },
  },
  unprotected: {
    s: { ingest: 'is-pass', input: 'is-bypass', llm: 'is-leak', output: 'is-bypass', disclosure: 'is-bypass', audit: 'is-none' },
    l: { 0: 'is-pass', 1: 'is-bypass', 2: 'is-bypass', 3: 'is-bypass', 4: 'is-bypass' },
  },
}

export default function LiveFire({ res, loading }: { res: ChatResponse | null; loading: boolean }) {
  const rootRef = useRef<HTMLDivElement>(null)
  const stageRefs = useRef<(HTMLDivElement | null)[]>([])
  const linkRefs = useRef<(HTMLSpanElement | null)[]>([])
  const packetRef = useRef<HTMLSpanElement>(null)

  const model = res && !('error' in res) ? read(res, res.guard) : null

  useLayoutEffect(() => {
    if (!model || !rootRef.current) return
    const root = rootRef.current
    const stages = stageRefs.current
    const links = linkRefs.current
    const packet = packetRef.current
    const railEl = root.querySelector('.lf-rail')

    const railY = (i: number) => {
      const icon = stages[i]?.querySelector('.lf-stage__icon')
      if (!icon || !railEl) return 0
      const r = icon.getBoundingClientRect()
      const rr = railEl.getBoundingClientRect()
      return r.top - rr.top + r.height / 2
    }
    const setStage = (key: StageKey, cls: string) => {
      const el = stages[IDX[key]]
      if (el) el.className = 'lf-stage ' + cls
    }
    const setLink = (i: number, cls: string) => {
      const el = links[i]
      if (el) el.className = 'lf-link ' + cls
    }
    const showRead = (key: StageKey) => {
      const el = stages[IDX[key]]?.querySelector('.lf-stage__read')
      if (el) gsap.to(el, { opacity: 1, x: 0, duration: 0.28, ease: 'power2.out' })
    }

    const reads = root.querySelectorAll('.lf-stage__read')
    const reveals = root.querySelectorAll('.lf-reveal')
    const inks = root.querySelectorAll('.lf-redacted, .lf-leak')

    // hard reset to a clean slate
    stages.forEach((el) => el && (el.className = 'lf-stage'))
    links.forEach((el) => el && (el.className = 'lf-link'))
    gsap.set(reads, { opacity: 0, x: -4 })
    gsap.set(reveals, { opacity: 0, y: 8 })
    gsap.set(packet, { opacity: 0, scale: 1, y: railY(IDX.ingest) })
    inks.forEach((el) => el.classList.remove('is-on'))

    const applyFinal = () => {
      const f = FINAL[model.kind]
      Object.entries(f.s).forEach(([k, c]) => setStage(k as StageKey, c))
      Object.entries(f.l).forEach(([i, c]) => setLink(+i, c))
      gsap.set(packet, { opacity: 0 })
      gsap.set(reads, { opacity: 1, x: 0 })
      gsap.set(reveals, { opacity: 1, y: 0 })
      inks.forEach((el) => el.classList.add('is-on'))
    }

    const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches
    if (reduce || document.visibilityState === 'hidden') {
      applyFinal()
      return
    }

    const tl = gsap.timeline({ defaults: { ease: 'power3.out' } })

    // ingest
    tl.to(packet, { opacity: 1, duration: 0.2 })
    setStage('ingest', 'is-active')
    showRead('ingest')
    tl.add(() => {
      setStage('ingest', 'is-pass')
      setLink(IDX.ingest, 'is-pass')
    })

    // travel to input detection
    tl.to(packet, { y: railY(IDX.input), duration: 0.5 })
    tl.add(() => setStage('input', 'is-active'))
    tl.to({ v: 0 }, { v: 1, duration: 0.35 })

    if (model.kind === 'blocked') {
      tl.add(() => {
        setStage('input', 'is-block')
        setLink(IDX.input, 'is-severed')
        showRead('input')
      })
      tl.to(packet, { scale: 1.7, duration: 0.18, yoyo: true, repeat: 1 })
      tl.to(packet, { opacity: 0, duration: 0.2 }, '+=0.05')
      tl.add(() => {
        ;(['llm', 'output', 'disclosure'] as StageKey[]).forEach((k) => setStage(k, 'is-skip'))
        ;[IDX.llm, IDX.output, IDX.disclosure].forEach((i) => setLink(i, 'is-severed'))
      })
      // the evidence drops straight to the sealed audit record
      tl.to(packet, { opacity: 1, scale: 1, y: railY(IDX.audit), duration: 0.42 }, '+=0.05')
      tl.add(() => setStage('audit', 'is-seal'))
    } else if (model.kind === 'unprotected') {
      tl.add(() => {
        setStage('input', 'is-bypass')
        setLink(IDX.input, 'is-bypass')
        showRead('input')
      })
      tl.to(packet, { y: railY(IDX.llm), duration: 0.46 })
      tl.add(() => setStage('llm', 'is-active'))
      tl.to({ v: 0 }, { v: 1, duration: 0.5 }) // thinking
      tl.add(() => {
        setStage('llm', 'is-leak')
        setLink(IDX.llm, 'is-bypass')
        showRead('llm')
      })
      tl.to(packet, { y: railY(IDX.output), duration: 0.42 })
      tl.add(() => {
        setStage('output', 'is-bypass')
        setStage('disclosure', 'is-bypass')
        setStage('audit', 'is-none')
        ;[IDX.output, IDX.disclosure].forEach((i) => setLink(i, 'is-bypass'))
        showRead('output')
        showRead('disclosure')
        showRead('audit')
      })
      tl.to(packet, { opacity: 0, duration: 0.3 })
    } else {
      // sanitized | allowed
      tl.add(() => {
        setStage('input', 'is-pass')
        setLink(IDX.input, 'is-pass')
        showRead('input')
      })
      tl.to(packet, { y: railY(IDX.llm), duration: 0.46 })
      tl.add(() => setStage('llm', 'is-active'))
      tl.to({ v: 0 }, { v: 1, duration: 0.5 })
      tl.add(() => {
        setStage('llm', 'is-pass')
        setLink(IDX.llm, 'is-pass')
        showRead('llm')
      })
      tl.to(packet, { y: railY(IDX.output), duration: 0.46 })
      tl.add(() => setStage('output', 'is-active'))
      tl.to({ v: 0 }, { v: 1, duration: 0.3 })
      tl.add(() => {
        setStage('output', model.kind === 'sanitized' ? 'is-warn' : 'is-pass')
        setLink(IDX.output, 'is-pass')
        showRead('output')
      })
      tl.to(packet, { y: railY(IDX.disclosure), duration: 0.42 })
      tl.add(() => {
        setStage('disclosure', 'is-pass')
        setLink(IDX.disclosure, 'is-pass')
        showRead('disclosure')
      })
      tl.to(packet, { y: railY(IDX.audit), duration: 0.42 })
      tl.add(() => setStage('audit', 'is-seal'))
    }

    // reveal the readout (verdict, reply, seal, ai-act)
    tl.add(() => showRead('audit'))
    tl.to(reveals, { opacity: 1, y: 0, duration: 0.4, stagger: 0.08 }, '-=0.1')
    // the hash seal snaps shut
    tl.add(() => {
      const lock = root.querySelector('.lf-seal__lock')
      if (lock) gsap.fromTo(lock, { scale: 0.6 }, { scale: 1, duration: 0.5, ease: 'power3.out' })
    }, '-=0.2')
    // redaction bars / exposed-secret ink stamp in
    tl.add(() => inks.forEach((el, i) => gsap.delayedCall(i * 0.06, () => el.classList.add('is-on'))))
    if (model.kind !== 'unprotected') {
      tl.to(packet, { opacity: 0, duration: 0.3 }, '+=0.2')
    }

    // if the tab goes hidden mid-run rAF pauses — snap to the final state
    const onVis = () => {
      if (document.visibilityState === 'hidden') {
        tl.kill()
        applyFinal()
      }
    }
    document.addEventListener('visibilitychange', onVis)

    return () => {
      document.removeEventListener('visibilitychange', onVis)
      tl.kill()
    }
  }, [res]) // eslint-disable-line react-hooks/exhaustive-deps

  // ---- render --------------------------------------------------------------
  if (!res && !loading) {
    return (
      <div className="livefire livefire--idle">
        <div className="lf-idle">
          <div className="lf-idle__rail" aria-hidden="true">
            {STAGES.map((s) => (
              <span className="lf-idle__node" key={s.key}>
                <svg viewBox="0 0 20 20">{s.icon}</svg>
              </span>
            ))}
          </div>
          <p>
            Fire a prompt. The input verdict, model reply, output scan, AI-Act disclosure
            and the sealed audit record light up this pipeline in real time.
          </p>
        </div>
      </div>
    )
  }

  if (res && 'error' in res) {
    return (
      <div className="livefire">
        <div className="lf-banner lf-banner--blocked">
          <span className="lf-banner__tag">REQUEST FAILED</span>
          <span className="lf-banner__text">Is the AEGIS backend running on :8000?</span>
        </div>
      </div>
    )
  }

  const reply = res ? String(res.reply || '') : ''
  const disclosed = reply.startsWith(DISCLOSURE)
  const body = disclosed ? reply.slice(DISCLOSURE.length).trim() : reply
  const m = model

  return (
    <div className={'livefire' + (m ? ' livefire--' + m.kind : '') + (loading ? ' is-loading' : '')} ref={rootRef}>
      <div className="lf-rail">
        <span className="lf-spine" aria-hidden="true" />
        {STAGES.map((s, i) => (
          <div className="lf-stage" key={s.key} ref={(el) => (stageRefs.current[i] = el)}>
            <span className="lf-stage__icon">
              <svg viewBox="0 0 20 20" aria-hidden="true">
                {s.icon}
              </svg>
            </span>
            <div className="lf-stage__text">
              <span className="lf-stage__title">{s.title}</span>
              <span className="lf-stage__sub mono">{s.sub}</span>
            </div>
            <span className="lf-stage__read mono">{m ? m.reads[s.key] : ''}</span>
            {i < STAGES.length - 1 && (
              <span className="lf-link" ref={(el) => (linkRefs.current[i] = el)} aria-hidden="true" />
            )}
          </div>
        ))}
        <span className="lf-packet" ref={packetRef} aria-hidden="true" />
      </div>

      {!m && loading && <p className="lf-wait mono">inspecting the request…</p>}

      {m && (
        <div className="lf-readout">
          <div className={'lf-banner lf-reveal lf-banner--' + m.kind}>
            <span className="lf-banner__tag">{m.banner.tag}</span>
            <span className="lf-banner__text">{m.banner.text}</span>
          </div>

          {m.detection && (m.kind === 'blocked' || m.kind === 'sanitized') && (
            <div className="lf-detect lf-reveal">
              <VerdictBadge verdict={m.detection.verdict} />
              {m.detection.severity != null && <Sev value={m.detection.severity} />}
              {m.detection.owasp_id && <span className="lf-meta mono">{m.detection.owasp_id}</span>}
              {m.detection.atlas_id && <span className="lf-meta mono">{m.detection.atlas_id}</span>}
              {m.detection.judge_used && <span className="lf-meta lf-meta--judge mono">LLM judge</span>}
            </div>
          )}

          <div className={'lf-reply lf-reveal lf-reply--' + m.kind}>
            {disclosed && (
              <span className="lf-disclosure mono" title="EU AI Act Art. 50 transparency">
                ⬡ AI-GENERATED
              </span>
            )}
            <p className="lf-reply__body">
              {m.kind === 'sanitized'
                ? splitRedactions(body).map((p, i) =>
                    p.redacted ? (
                      <span className="lf-redacted" key={i}>
                        REDACTED
                      </span>
                    ) : (
                      <span key={i}>{p.t}</span>
                    )
                  )
                : m.kind === 'unprotected'
                ? splitLeaks(body).map((p, i) =>
                    p.leak ? (
                      <span className="lf-leak" key={i}>
                        {p.t}
                      </span>
                    ) : (
                      <span key={i}>{p.t}</span>
                    )
                  )
                : body}
            </p>
          </div>

          {m.sealed ? (
            <div className="lf-seal lf-reveal">
              <span className="lf-seal__lock" aria-hidden="true">
                <svg viewBox="0 0 20 20">{ICON.lock}</svg>
              </span>
              <div className="lf-seal__hashes mono">
                <span className="lf-seal__id">#{String(m.sealed.id).padStart(3, '0')}</span>
                <span className="lf-seal__row">
                  <span className="lf-seal__k">prev</span>
                  {shortHash(m.sealed.prev_hash)}…
                </span>
                <span className="lf-seal__row is-self">
                  <span className="lf-seal__k">hash</span>
                  {shortHash(m.sealed.hash)}…
                </span>
              </div>
              <span className="lf-seal__state mono">SHA-256 · sealed</span>
            </div>
          ) : (
            m.kind === 'unprotected' && (
              <div className="lf-seal lf-seal--none lf-reveal">
                <span className="lf-seal__state mono">no record — nothing was logged</span>
              </div>
            )
          )}

          <div className="lf-act lf-reveal">
            {m.detection?.ai_act && <ArtChip article={m.detection.ai_act} />}
            {disclosed && <ArtChip article="Art.50" />}
            {m.sealed && <ArtChip article="Art.12" />}
            {m.kind === 'unprotected' && (
              <span className="lf-act__none mono">no AI-Act evidence produced</span>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
